version: "3"

services:
  wagateway:
    build:
      context: .
    image: beniepedia/wa-gateway:1.0
    container_name: wagateway
    restart: always
    ports:
      - 8888:5000
    environment:
      KEY: beniepedia
    volumes:
      - wa_credentials:/wa_credentials
    networks:
      - backend

volumes:
  wa_credentials:
    driver: local
    name: wa_credentials

networks:
  backend:
    external: true
